const model = {
  filter: [],
  filterCats: [
    { cat: "Architecture", checked: false },
    { cat: "Building", checked: false },
    { cat: "Completed", checked: false },
    { cat: "Collaboration", checked: false },
    { cat: "Surrealism", checked: false },
    { cat: "Art", checked: false },
    { cat: "Exhibition", checked: false },
    { cat: "Collage", checked: false },
    { cat: "Digital", checked: false },
    { cat: "Sculpture", checked: false },
    { cat: "3Dprint", checked: false },
    { cat: "3Dmodeling", checked: false },
    { cat: "Utopic", checked: false },
  ],
  filteredList: [],
  pictures: [
    {
      img: "IMG/PICTURES/Pro1_1.jpg",
      toggled: false,
      projectName: "Home Atelier",
      projectNumber: 1,
      title: "Home Atelier 1",
      description: "Arkitekturbygning ferdiglaget.",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Building", "Completed"],
      comments: [
        {
          email: "somemail@dom.com",
          user: "Knut Arild",
          comment: "Dette var lekkert! 10/10.",
          date: "15/2 - 23",
        },
        {
          email: "somemail@dom.com",
          user: "Bjarnulf",
          comment:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
          date: "15/2 - 23",
        },
        {
          email: "somemail@dom.com",
          user: "Bjarnulf",
          comment:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
          date: "15/2 - 23",
        },
        {
          email: "somemail@dom.com",
          user: "Bjarnulf",
          comment:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
          date: "15/2 - 23",
        },
        {
          email: "somemail@dom.com",
          user: "Bjarnulf",
          comment:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
          date: "15/2 - 23",
        },
      ],
    },
    {
      img: "IMG/PICTURES/Pro1_2.jpg",
      toggled: false,
      projectName: "Home Atelier",
      projectNumber: 1,
      title: "Home Atelier 2",
      description: "Arkitekturbygning ferdiglaget.",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Building", "Completed"],
      comments: [
        {
          email: "somemail@dom.com",
          user: "Bjarnulf",
          comment:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
          date: "15/2 - 23",
        },
      ],
    },
    {
      img: "IMG/PICTURES/Pro1_3.jpg",
      toggled: false,
      projectName: "Home Atelier",
      projectNumber: 1,
      title: "Home Atelier 3",
      description: "Arkitekturbygning ferdiglaget.",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Building", "Completed", "Collaboration"],
      comments: [],
    },
    {
      img: "IMG/PICTURES/Pro2_1.jpg",
      toggled: false,
      projectName: "Exhibition",
      projectNumber: 2,
      title: "Exhibition 1",
      description: "Framvist kunst.",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Surrealism", "Art", "Exhibition"],
      comments: [],
    },
    {
      img: "IMG/PICTURES/Pro2_2.jpg",
      toggled: false,
      projectName: "Exhibition",
      projectNumber: 2,
      title: "Exhibition 2",
      description: "Framvist kunst.",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Surrealism", "Art", "Exhibition"],
      comments: [],
    },
    {
      img: "IMG/PICTURES/Pro2_3.jpg",
      toggled: false,
      projectName: "Exhibition",
      projectNumber: 2,
      title: "Exhibition 3",
      description: "Framvist kunst.",
      artist: "Jarand Midtgaard",
      category: [
        "Architecture",
        "Surrealism",
        "Art",
        "Exhibition",
        "Collaboration",
      ],
      comments: [],
    },

    {
      img: "IMG/PICTURES/Pro3_1.jpg",
      toggled: false,
      projectName: "Digital Collage",
      projectNumber: 3,
      title: "Digital Collages 1",
      description: "Surrealistisk bildet laget digitalt.",
      artist: "Jarand Midtgaard",
      category: ["Surrealism", "Art", "Collage", "Digital"],
      comments: [],
    },
    {
      img: "IMG/PICTURES/Pro3_2.jpg",
      toggled: false,
      projectName: "Digital Collage",
      projectNumber: 3,
      title: "Digital Collages 2",
      description: "Surrealistisk bildet laget digitalt.",
      artist: "Jarand Midtgaard",
      category: ["Surrealism", "Art", "Collage", "Digital"],
      comments: [],
    },
    {
      img: "IMG/PICTURES/Pro3_3.jpg",
      toggled: false,
      projectName: "Digital Collage",
      projectNumber: 3,
      title: "Digital Collages 3",
      description: "Surrealistisk bildet laget digitalt.",
      artist: "Jarand Midtgaard",
      category: ["Surrealism", "Art", "Collage", "Digital", "Collaboration"],
      comments: [],
    },

    {
      img: "IMG/PICTURES/Pro4_1.jpg",
      toggled: false,
      projectName: "3D Print",
      projectNumber: 4,
      title: "Sculptures 1",
      description: "Printed architectural sculpture.",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Surrealism", "Sculpture", "3Dprint"],
      comments: [],
    },
    {
      img: "IMG/PICTURES/Pro4_2.jpg",
      toggled: false,
      projectName: "3D Print",
      projectNumber: 4,
      title: "Sculptures 2",
      description: "Printed architectural sculpture.",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Surrealism", "Sculpture", "3Dprint"],
      comments: [],
    },
    {
      img: "IMG/PICTURES/Pro4_3.jpg",
      toggled: false,
      projectName: "3D Print",
      projectNumber: 4,
      title: "Sculptures 3",
      description: "Printed architectural sculpture.",
      artist: "Jarand Midtgaard",
      category: [
        "Architecture",
        "Surrealism",
        "Sculpture",
        "3Dprint",
        "Collaboration",
      ],
      comments: [],
    },

    {
      img: "IMG/PICTURES/Pro5_1.JPG",
      toggled: false,
      projectName: "Architectural projects",
      projectNumber: 5,
      title: "Architectural Projects projects 1",
      description: "",
      artist: "Jarand Midtgaard",
      category: [
        "Architecture",
        "Surrealism",
        "3Dmodeling",
        "Utopic",
        "Collaboration",
      ],
      comments: [],
    },
    {
      img: "IMG/PICTURES/Pro5_2.jpg",
      toggled: false,
      projectName: "Architectural projects",
      projectNumber: 5,
      title: "Architectural Projects projects 2",
      description: "",
      artist: "Jarand Midtgaard",
      category: ["Architecture", "Surrealism", "3Dmodeling", "Utopic"],
      comments: [],
    },
    {
      img: "IMG/PICTURES/Pro5_3.JPG",
      toggled: false,
      projectName: "Architectural projects",
      projectNumber: 5,
      title: "Architectural Projects projects 3",
      description: "",
      artist: "Jarand Midtgaard",
      category: [
        "Architecture",
        "Surrealism",
        "3Dmodeling",
        "Utopic",
        "Collaboration",
      ],
      comments: [],
    },
  ],
};
